public enum TokenType {
    INTEIRO, REAL, VARIAVEL, NUMINT, NUMREAL, LEFT_PAR, RIGHT_PAR, E, OU, LER, IMPRIMIR, CADEIA,
    SE, ENTAO, SENAO, ENQUANTO, INICIO, FIM, DOIS_PONTOS,
    SOMA, SUBTRACAO, MULTIPLICACAO, DIVISAO,
    MAIOR_QUE, MAIOR_OU_IGUAL_QUE, MENOR_QUE, MENOR_OU_IGUAL_QUE, DIFERENTE, IGUAL,
    ID, DESCONHECIDO
}